export { default as About} from './About'
export { default as Programs} from './Programs'
export { default as Pricing} from './Pricing'
export {default as Instructors} from './Instructors'
export {default as Testimonials} from './Testimonials'